# Generated by Django 4.0.5 on 2022-06-19 01:23

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0002_remove_business_location_remove_userprofile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policedept',
            name='chief',
        ),
        migrations.AddField(
            model_name='chama',
            name='address',
            field=django_google_maps.fields.AddressField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='healthdept',
            name='address',
            field=django_google_maps.fields.AddressField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='policedept',
            name='address',
            field=django_google_maps.fields.AddressField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='policedept',
            name='policechief',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='userpost',
            name='address',
            field=django_google_maps.fields.AddressField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='PoliceChief',
        ),
    ]
