# Generated by Django 4.0.5 on 2022-06-20 03:39

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0004_rename_owner_business_user_business_hood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='address',
            new_name='hood_name',
        ),
        migrations.AlterField(
            model_name='userhood',
            name='name',
            field=django_google_maps.fields.AddressField(default='', max_length=200),
        ),
    ]
