# Generated by Django 4.0.5 on 2022-06-20 09:23

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0008_location_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.AddField(
            model_name='location',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=django_google_maps.fields.AddressField(default='', max_length=200),
        ),
    ]
