# Generated by Django 4.0.5 on 2022-06-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0009_remove_location_city_location_geolocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='geolocation',
        ),
    ]
