# Generated by Django 4.0.5 on 2022-06-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0011_remove_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='display_name',
        ),
    ]
