# Generated by Django 4.0.5 on 2022-06-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0012_remove_userprofile_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policedept',
            old_name='policechief',
            new_name='police_chief',
        ),
    ]
