# Generated by Django 4.0.5 on 2022-06-21 01:27

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0013_rename_policechief_policedept_police_chief'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdept',
            name='hood',
            field=django_google_maps.fields.AddressField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='policedept',
            name='hood',
            field=django_google_maps.fields.AddressField(default='', max_length=200),
        ),
    ]
