# Generated by Django 4.0.5 on 2022-06-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0014_healthdept_hood_policedept_hood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.PositiveIntegerField(default=254),
        ),
    ]
