# Generated by Django 4.0.5 on 2022-06-21 04:33

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0016_remove_userpost_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoodUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_hood_name', django_google_maps.fields.AddressField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_address', django_google_maps.fields.AddressField(default='', max_length=200)),
            ],
        ),
    ]
