# Generated by Django 4.0.5 on 2022-06-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0017_hoodupdate_locationupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='occupants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
